<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>ExusiAI.FileViewer.Desktop</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExusiAI.FileViewer.Core\ExusiAI.FileViewer.Core.csproj" />
  </ItemGroup>
</Project>
